// Généré le 2026-10-03 à partir de wikily.gg (niveaux de capacité Homeland de chaque Aniimo, noms FR).
// n = nom FR, en = nom EN, f = forme (absent = forme de base ou formes identiques), a = {capacité: niveau}.
export const ANIIMO = [
    { n: "Algobulle", en: "Bubbeep", a: { Grass: 1, Water: 1 } },
    { n: "Algoglam", en: "Glameep", a: { Grass: 3, Water: 3 } },
    { n: "Algoglam", en: "Glameep", f: "Forme prismana", a: { Grass: 3, Dark: 3, Hauling: 1 } },
    { n: "Astor", en: "Sheldon", a: { Water: 2, Leisure: 2 } },
    { n: "Astrid", en: "Shelly", a: { Water: 1, Leisure: 1 } },
    { n: "Astrophel", en: "Sherro", a: { Water: 3, Leisure: 3 } },
    { n: "Astrophel", en: "Sherro", f: "Forme prismana", a: { Water: 4, Light: 3, Leisure: 4 } },
    { n: "Astrophel", en: "Sherro", f: "Forme des orages", a: { Water: 3, Lightning: 2, Leisure: 3 } },
    { n: "Astrophel", en: "Sherro", f: "Forme Ombrarc", a: { Water: 3, Light: 3, Leisure: 3 } },
    { n: "Balabée", en: "Baleetle", a: { Earth: 1, Hauling: 1 } },
    { n: "Balabée", en: "Baleetle", f: "Forme des neiges", a: { Earth: 1, Ice: 1, Hauling: 1 } },
    { n: "Bastiroc", en: "Bailite", a: { Earth: 3, Hauling: 3 } },
    { n: "Boulabée", en: "Bouldus", a: { Earth: 3, Hauling: 3 } },
    { n: "Boulabée", en: "Bouldus", f: "Forme des neiges", a: { Earth: 3, Ice: 2, Hauling: 3 } },
    { n: "Bourgeonnet", en: "Budsquire", a: { Grass: 1, Artisanship: 1 } },
    { n: "Bulbi", en: "Bulbly", a: { Lightning: 1, Artisanship: 1 } },
    { n: "Bulloutre", en: "Popota", a: { Water: 2, Leisure: 2 } },
    { n: "Cabaroc", en: "Cozite", a: { Earth: 1, Hauling: 1 } },
    { n: "Casquillon", en: "Rookey", a: { Dark: 3, Hauling: 3 } },
    { n: "Casquillon", en: "Rookey", f: "Forme des neiges", a: { Ice: 2, Dark: 3, Hauling: 3 } },
    { n: "Casquimord", en: "Helmwhelp", a: { Wind: 2, Hauling: 2 } },
    { n: "Casquimou", en: "Helmut", a: { Dark: 1, Hauling: 1 } },
    { n: "Casquimou", en: "Helmut", f: "Forme des neiges", a: { Ice: 1, Dark: 1, Hauling: 1 } },
    { n: "Casquipreux", en: "Pawney", a: { Dark: 3, Hauling: 3 } },
    { n: "Casquipreux", en: "Pawney", f: "Forme prismana", a: { Dark: 4, Hauling: 4 } },
    { n: "Casquipreux", en: "Pawney", f: "Forme des neiges", a: { Ice: 2, Dark: 3, Hauling: 3 } },
    { n: "Casquipreux", en: "Pawney", f: "Forme Ombrarc", a: { Dark: 3, Hauling: 1 } },
    { n: "Clairbec", en: "Cornet", a: { Wind: 3 } },
    { n: "Clairbec", en: "Cornet", f: "Forme des plages", a: { Water: 2, Wind: 3 } },
    { n: "Clairbec", en: "Cornet", f: "Hautes-plaines", a: { Grass: 2, Wind: 3 } },
    { n: "Clairbec", en: "Cornet", f: "Forme prismana", a: { Lightning: 3, Wind: 4 } },
    { n: "Clairbec", en: "Cornet", f: "Forme Ombrarc", a: { Lightning: 3, Wind: 3 } },
    { n: "Coléobée", en: "Waleetle", a: { Earth: 3, Hauling: 3 } },
    { n: "Coléobée", en: "Waleetle", f: "Forme prismana", a: { Earth: 4, Dark: 3, Hauling: 4 } },
    { n: "Coléobée", en: "Waleetle", f: "Forme des neiges", a: { Earth: 3, Ice: 2, Hauling: 3 } },
    { n: "Coracroc", en: "Reefish", a: { Water: 1, Earth: 1 } },
    { n: "Coracroc", en: "Reefish", f: "Forme des déluges", a: { Earth: 1 } },
    { n: "Coraleurre", en: "Coraliz", a: { Water: 1, Earth: 1, Hauling: 1 } },
    { n: "Coraleurre", en: "Coraliz", f: "Forme des déluges", a: { Earth: 1, Hauling: 1 } },
    { n: "Crabiflore", en: "Shrubclaw", a: { Grass: 2, Earth: 3, Hauling: 3 } },
    { n: "Crabiflore", en: "Shrubclaw", f: "Forme des baies / Forme des plages / Forme des vasières", a: { Earth: 3, Hauling: 3 } },
    { n: "Crabourgeon", en: "Budclaw", a: { Grass: 1, Earth: 1, Hauling: 1 } },
    { n: "Crabourgeon", en: "Budclaw", f: "Forme des baies / Forme des plages / Forme des vasières", a: { Earth: 1, Hauling: 1 } },
    { n: "Cristocrabe", en: "Geoclaw", a: { Ice: 3, Hauling: 3 } },
    { n: "Cristorex", en: "Minespine", a: { Earth: 3, Hauling: 3 } },
    { n: "Cuicui", en: "Chirpi", a: { Wind: 1 } },
    { n: "Cuicui", en: "Chirpi", f: "Forme des plages", a: { Water: 1, Wind: 1 } },
    { n: "Cuicui", en: "Chirpi", f: "Hautes-plaines", a: { Grass: 1, Wind: 1 } },
    { n: "Cuiragon", en: "Helgon", a: { Wind: 3, Hauling: 3 } },
    { n: "Cumulaine", en: "Nimbi", a: { Wind: 1, Leisure: 1 } },
    { n: "Cumulaine", en: "Nimbi", f: "Forme des plateaux", a: { Ice: 1, Wind: 1, Leisure: 1 } },
    { n: "Cumulaine", en: "Nimbi", f: "Forme des déluges", a: { Lightning: 1, Wind: 1, Leisure: 1 } },
    { n: "Célestia", en: "Celestis", a: { Dark: 1, Leisure: 1 } },
    { n: "Danzard", en: "Dazmand", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Eko", en: "Eko", a: { Wind: 1, Artisanship: 1 } },
    { n: "Ekolombo", en: "Eklue", a: { Wind: 3, Artisanship: 3 } },
    { n: "Elfe solidaire", en: "Sparkelf", a: { Fire: 3 } },
    { n: "Elfe solidaire", en: "Sparkelf", f: "Forme prismana", a: { Fire: 4 } },
    { n: "Fabulle", en: "Erlath", a: { Water: 3 } },
    { n: "Falou", en: "Fahloo", a: { Water: 1 } },
    { n: "Farfafeu", en: "Sparki", a: { Fire: 2 } },
    { n: "Fennelune", en: "Fennelun", a: { Light: 3, Hauling: 3 } },
    { n: "Filoutus", en: "Pranky", a: { Water: 2, Hauling: 2 } },
    { n: "Filoutus", en: "Pranky", f: "Forme des neiges", a: { Water: 2, Ice: 1, Hauling: 2 } },
    { n: "Flamirage", en: "Flamerion", a: { Fire: 3 } },
    { n: "Flammi", en: "Wisptis", a: { Dark: 1, Artisanship: 1 } },
    { n: "Flammi", en: "Wisptis", f: "Forme des forêts", a: { Grass: 1, Dark: 1, Artisanship: 1 } },
    { n: "Flammi", en: "Wisptis", f: "Hautes-plaines", a: { Fire: 1, Dark: 1, Artisanship: 1 } },
    { n: "Fluoretti", en: "Flutternym", a: { Wind: 1, Leisure: 1 } },
    { n: "Fluoretti", en: "Flutternym", f: "Forme des montagnes boisées", a: { Earth: 1, Wind: 1, Leisure: 1 } },
    { n: "Fluoretti", en: "Flutternym", f: "Forme nocturne", a: { Wind: 1, Dark: 1, Leisure: 1 } },
    { n: "Fluoretti", en: "Flutternym", f: "Forme des mers florales", a: { Grass: 1, Wind: 1, Leisure: 1 } },
    { n: "Fragrancier", en: "Fragrancier", a: { Dark: 3, Leisure: 3, Perfumery: 3 } },
    { n: "Fredon", en: "Hummin", a: { Grass: 1 } },
    { n: "Fulgucrin", en: "Fenmane", a: { Lightning: 3, Hauling: 3 } },
    { n: "Fulgucrin", en: "Fenmane", f: "Forme prismana", a: { Lightning: 4, Light: 3, Hauling: 3, Artisanship: 4 } },
    { n: "Fulmi", en: "Fulmintis", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Fulmi", en: "Fulmintis", f: "Forme prismana", a: { Lightning: 4, Light: 3, Artisanship: 4 } },
    { n: "Gachapoulpe", en: "Gachapus", a: { Water: 3, Artisanship: 3 } },
    { n: "Givrotus", en: "Glacy", a: { Water: 3, Ice: 2, Hauling: 3 } },
    { n: "Givrotus", en: "Glacy", f: "Forme prismana", a: { Water: 4, Light: 3, Hauling: 4 } },
    { n: "Glaivrier", en: "Fenrier", a: { Ice: 2, Hauling: 2 } },
    { n: "Glaivrier", en: "Fenrier", f: "Forme nocturne", a: { Ice: 2, Dark: 1, Hauling: 2 } },
    { n: "Grizzo", en: "Grizbo", a: { Earth: 3, Hauling: 3 } },
    { n: "Grizzo", en: "Grizbo", f: "Forme prismana", a: { Earth: 4, Dark: 3, Hauling: 4 } },
    { n: "Géodosaure", en: "Geodeback", a: { Earth: 2, Hauling: 2 } },
    { n: "Hurlebrasier", en: "Scorchhowl", a: { Fire: 3, Hauling: 3 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Hautes-plaines", a: { Fire: 3, Earth: 2, Hauling: 3 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Forme prismana", a: { Fire: 4, Hauling: 4 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Forme des orages", a: { Fire: 3, Lightning: 2, Hauling: 3 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Forme Ombrarc", a: { Fire: 3, Hauling: 1 } },
    { n: "Hélion", en: "Helion", a: { Light: 3, Hauling: 3 } },
    { n: "Igniti", en: "Ignitis", a: { Dark: 3, Artisanship: 3 } },
    { n: "Igniti", en: "Ignitis", f: "Forme des forêts", a: { Grass: 2, Dark: 3, Artisanship: 3 } },
    { n: "Igniti", en: "Ignitis", f: "Hautes-plaines", a: { Fire: 2, Dark: 3, Artisanship: 3 } },
    { n: "Igniti", en: "Ignitis", f: "Forme prismana", a: { Fire: 3, Dark: 4, Artisanship: 4 } },
    { n: "Igniti", en: "Ignitis", f: "Forme Ombrarc", a: { Fire: 3, Dark: 3, Artisanship: 3 } },
    { n: "Infergon", en: "Infergon", a: { Fire: 3, Hauling: 3 } },
    { n: "Infergon", en: "Infergon", f: "Forme prismana", a: { Fire: 4, Wind: 3, Hauling: 4 } },
    { n: "Inferlupin", en: "Inferlupa", a: { Fire: 2, Dark: 3, Hauling: 3 } },
    { n: "Inferlupin", en: "Inferlupa", f: "Forme prismana", a: { Fire: 3, Dark: 4, Hauling: 4 } },
    { n: "Iris", en: "Iris", a: { Grass: 1, Leisure: 1 } },
    { n: "Jappardent", en: "Flameruff", a: { Fire: 2, Hauling: 2 } },
    { n: "Jappardent", en: "Flameruff", f: "Hautes-plaines", a: { Fire: 2, Earth: 1, Hauling: 2 } },
    { n: "Lainirique", en: "Dreaple", a: { Dark: 3, Leisure: 3 } },
    { n: "Lavasaure", en: "Lavazar", a: { Fire: 2, Earth: 1, Hauling: 2 } },
    { n: "Loufeuteau", en: "Emberpup", a: { Fire: 1, Hauling: 1 } },
    { n: "Loufeuteau", en: "Emberpup", f: "Hautes-plaines", a: { Fire: 1, Earth: 1, Hauling: 1 } },
    { n: "Louloutre", en: "Susuta", a: { Water: 1, Leisure: 1 } },
    { n: "Luminelle", en: "Luminelle", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Luminelle", en: "Luminelle", f: "Forme prismana", a: { Lightning: 4, Light: 3, Artisanship: 4 } },
    { n: "Luminelle", en: "Luminelle", f: "Forme des déluges", a: { Water: 2, Lightning: 3, Artisanship: 3 } },
    { n: "Luminelle", en: "Luminelle", f: "Forme Ombrarc", a: { Lightning: 4, Light: 4 } },
    { n: "Lumiris", en: "Irisalis", a: { Grass: 4, Leisure: 4 } },
    { n: "Lunara", en: "Lunara", a: { Light: 3, Hauling: 3 } },
    { n: "Magmarex", en: "Magmarex", a: { Fire: 3, Earth: 2, Hauling: 3 } },
    { n: "Magmarex", en: "Magmarex", f: "Forme prismana", a: { Fire: 4, Dark: 3, Hauling: 4 } },
    { n: "Magmarex", en: "Magmarex", f: "Forme Ombrarc", a: { Fire: 3, Dark: 3, Leisure: 3 } },
    { n: "Malaglace", en: "Malevsera", a: { Ice: 3, Artisanship: 3 } },
    { n: "Malange", en: "Malangel", a: { Ice: 1, Artisanship: 1 } },
    { n: "Mandibouille", en: "Jawling", a: { Wind: 1, Hauling: 1 } },
    { n: "Mimijoue", en: "Cheekie", a: { Ice: 1, Hauling: 1 } },
    { n: "Molosabre", en: "Glynsera", a: { Ice: 3, Hauling: 3 } },
    { n: "Molosabre", en: "Glynsera", f: "Forme nocturne", a: { Ice: 3, Dark: 2, Hauling: 3 } },
    { n: "Molosabre", en: "Glynsera", f: "Forme prismana", a: { Ice: 4, Light: 3, Hauling: 4 } },
    { n: "Morsou", en: "Wavwal", a: { Ice: 3, Hauling: 1 } },
    { n: "Méliflore", en: "Melloblum", a: { Grass: 3, Artisanship: 3 } },
    { n: "Méliflore", en: "Melloblum", f: "Forme prismana", a: { Grass: 4, Light: 3, Artisanship: 4 } },
    { n: "Nutrion", en: "Tuckin", a: { Grass: 3, Hauling: 3 } },
    { n: "Nutrion", en: "Tuckin", f: "Forme des montagnes", a: { Grass: 3, Earth: 2, Hauling: 3 } },
    { n: "Ondeloutre", en: "Piopiota", a: { Water: 3, Leisure: 3 } },
    { n: "Ondeloutre", en: "Piopiota", f: "Forme nocturne", a: { Water: 3, Dark: 2, Leisure: 3 } },
    { n: "Osky", en: "Bonesky", a: { Ice: 1, Hauling: 1 } },
    { n: "Osky", en: "Bonesky", f: "Forme nocturne", a: { Ice: 1, Dark: 1, Hauling: 1 } },
    { n: "Ourso", en: "Cubbo", a: { Earth: 1, Hauling: 1 } },
    { n: "Pebbling", en: "Pebbling", a: { Earth: 1, Hauling: 1 } },
    { n: "Plumiel", en: "Dewy", a: { Dark: 1, Leisure: 1, Perfumery: 1 } },
    { n: "Pomawk", en: "Pomawk", a: { Grass: 3, Artisanship: 3 } },
    { n: "Pomawk", en: "Pomawk", f: "Forme des neiges", a: { Grass: 3, Ice: 2, Artisanship: 3 } },
    { n: "Pomœuf", en: "Pomegg", a: { Grass: 1, Artisanship: 1 } },
    { n: "Pomœuf", en: "Pomegg", f: "Forme des neiges", a: { Grass: 1, Ice: 1, Artisanship: 1 } },
    { n: "Poulplash", en: "Popapus", a: { Water: 3 } },
    { n: "Pulsato", en: "Besauce", a: { Lightning: 3, Artisanship: 1 } },
    { n: "Rapiéronce", en: "Thornblade", a: { Grass: 3, Artisanship: 3 } },
    { n: "Rapiéronce", en: "Thornblade", f: "Forme prismana", a: { Grass: 4, Water: 3, Artisanship: 4 } },
    { n: "Rapiéronce", en: "Thornblade", f: "Forme des orages", a: { Grass: 3, Lightning: 2, Artisanship: 3 } },
    { n: "Rapiéronce", en: "Thornblade", f: "Forme Ombrarc", a: { Grass: 3, Water: 3, Artisanship: 3 } },
    { n: "Soléon", en: "Soleon", a: { Light: 3, Hauling: 3 } },
    { n: "Sorcelonde", en: "Hexxin", a: { Grass: 1, Dark: 2, Artisanship: 2 } },
    { n: "Sorcelonde", en: "Hexxin", f: "Forme prismana", a: { Grass: 3, Dark: 4, Artisanship: 4 } },
    { n: "Sorcelonde", en: "Hexxin", f: "Forme Ombrarc", a: { Grass: 2, Dark: 2 } },
    { n: "Stellaria", en: "Stellarys", a: { Dark: 3, Leisure: 3 } },
    { n: "Stellaria", en: "Stellarys", f: "Forme prismana", a: { Ice: 3, Dark: 4, Leisure: 4 } },
    { n: "Stellaria", en: "Stellarys", f: "Forme des déluges", a: { Water: 2, Dark: 3, Leisure: 3 } },
    { n: "Stellaria", en: "Stellarys", f: "Forme Ombrarc", a: { Ice: 3, Dark: 3, Leisure: 3 } },
    { n: "Terriloutre", en: "Panpanta", a: { Water: 3, Leisure: 3 } },
    { n: "Terriloutre", en: "Panpanta", f: "Forme prismana", a: { Water: 4, Leisure: 4 } },
    { n: "Tilotus", en: "Skippy", a: { Water: 1, Hauling: 1 } },
    { n: "Tilotus", en: "Skippy", f: "Forme des neiges", a: { Water: 1, Ice: 1, Hauling: 1 } },
    { n: "Touffu", en: "Fentuft", a: { Lightning: 1, Hauling: 1 } },
    { n: "Trombec", en: "Tromber", a: { Wind: 3 } },
    { n: "Trombec", en: "Tromber", f: "Forme des plages", a: { Water: 2, Wind: 3 } },
    { n: "Trombec", en: "Tromber", f: "Hautes-plaines", a: { Grass: 2, Wind: 3 } },
    { n: "Tubabec", en: "Tubster", a: { Wind: 3 } },
    { n: "Tubabec", en: "Tubster", f: "Forme des plages", a: { Water: 2, Wind: 3 } },
    { n: "Tubabec", en: "Tubster", f: "Hautes-plaines", a: { Grass: 2, Wind: 3 } },
    { n: "Turbulaine", en: "Turbo", a: { Wind: 3, Leisure: 3 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme des plateaux", a: { Ice: 2, Wind: 3, Leisure: 3 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme prismana", a: { Wind: 4, Dark: 3, Leisure: 4 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme des déluges", a: { Lightning: 2, Wind: 3, Leisure: 3 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme Ombrarc", a: { Wind: 3, Dark: 3, Leisure: 3 } },
    { n: "Valsiris", en: "Irisal", a: { Grass: 3, Leisure: 3 } },
    { n: "Valsiris", en: "Irisal", f: "Forme prismana", a: { Grass: 4, Leisure: 4 } },
    { n: "Vitti", en: "Somniwing", a: { Grass: 4, Wind: 3, Leisure: 4 } },
    { n: "Voilotus", en: "Leafy", a: { Grass: 3, Water: 2, Hauling: 3 } },
    { n: "Voilueur", en: "Veilfloat", a: { Lightning: 2, Artisanship: 2 } },
    { n: "Voletti", en: "Gracewing", a: { Wind: 3, Leisure: 3 } },
    { n: "Voletti", en: "Gracewing", f: "Forme des montagnes boisées", a: { Earth: 2, Wind: 3, Leisure: 3 } },
    { n: "Voletti", en: "Gracewing", f: "Forme nocturne", a: { Wind: 3, Dark: 2, Leisure: 3 } },
    { n: "Voletti", en: "Gracewing", f: "Forme des mers florales", a: { Grass: 2, Wind: 3, Leisure: 3 } },
    { n: "Voltige", en: "Bolty", a: { Lightning: 1, Artisanship: 1 } },
    { n: "Voltignasse", en: "Blazen", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Voltignasse", en: "Blazen", f: "Forme prismana", a: { Lightning: 4, Dark: 3, Artisanship: 4 } },
    { n: "Voltignasse", en: "Blazen", f: "Forme Ombrarc", a: { Lightning: 3, Dark: 3, Artisanship: 3 } },
    { n: "Écurixe", en: "Squarrel", a: { Fire: 1, Artisanship: 1 } },
    { n: "Écurouste", en: "Squashel", a: { Fire: 2, Artisanship: 2 } },
];

export const ANIIMO_SOURCE = { name: 'wikily.gg', url: 'https://wikily.gg/fr/aniimo/aniilog', date: '2026-10-03' };
