// Généré le 2026-10-03 à partir de wikily.gg (niveaux de capacité Homeland de chaque Aniimo, noms FR).
// n = nom FR, en = nom EN, f = forme (absent = forme de base ou formes identiques), i = icône (aniimo-icons/<i>.webp), a = {capacité: niveau}.
export const ANIIMO = [
    { n: "Algobulle", en: "Bubbeep", i: "bubbeep", a: { Grass: 1, Water: 1 } },
    { n: "Algoglam", en: "Glameep", i: "glameep", a: { Grass: 3, Water: 3 } },
    { n: "Algoglam", en: "Glameep", f: "Forme prismana", i: "glameep-prismana-form", a: { Grass: 3, Dark: 3, Hauling: 1 } },
    { n: "Astor", en: "Sheldon", i: "sheldon", a: { Water: 2, Leisure: 2 } },
    { n: "Astrid", en: "Shelly", i: "shelly", a: { Water: 1, Leisure: 1 } },
    { n: "Astrophel", en: "Sherro", i: "sherro", a: { Water: 3, Leisure: 3 } },
    { n: "Astrophel", en: "Sherro", f: "Forme prismana", i: "sherro-prismana-form", a: { Water: 4, Light: 3, Leisure: 4 } },
    { n: "Astrophel", en: "Sherro", f: "Forme des orages", i: "sherro-thunderstorm-form", a: { Water: 3, Lightning: 2, Leisure: 3 } },
    { n: "Astrophel", en: "Sherro", f: "Forme Ombrarc", i: "sherro-umbrabow-form", a: { Water: 3, Light: 3, Leisure: 3 } },
    { n: "Balabée", en: "Baleetle", i: "baleetle", a: { Earth: 1, Hauling: 1 } },
    { n: "Balabée", en: "Baleetle", f: "Forme des neiges", i: "baleetle-snowfield-form", a: { Earth: 1, Ice: 1, Hauling: 1 } },
    { n: "Bastiroc", en: "Bailite", i: "bailite", a: { Earth: 3, Hauling: 3 } },
    { n: "Boulabée", en: "Bouldus", i: "bouldus", a: { Earth: 3, Hauling: 3 } },
    { n: "Boulabée", en: "Bouldus", f: "Forme des neiges", i: "bouldus-snowfield-form", a: { Earth: 3, Ice: 2, Hauling: 3 } },
    { n: "Bourgeonnet", en: "Budsquire", i: "budsquire", a: { Grass: 1, Artisanship: 1 } },
    { n: "Bulbi", en: "Bulbly", i: "bulbly", a: { Lightning: 1, Artisanship: 1 } },
    { n: "Bulloutre", en: "Popota", i: "popota", a: { Water: 2, Leisure: 2 } },
    { n: "Cabaroc", en: "Cozite", i: "cozite", a: { Earth: 1, Hauling: 1 } },
    { n: "Casquillon", en: "Rookey", i: "rookey", a: { Dark: 3, Hauling: 3 } },
    { n: "Casquillon", en: "Rookey", f: "Forme des neiges", i: "rookey-snowfield-form", a: { Ice: 2, Dark: 3, Hauling: 3 } },
    { n: "Casquimord", en: "Helmwhelp", i: "helmwhelp", a: { Wind: 2, Hauling: 2 } },
    { n: "Casquimou", en: "Helmut", i: "helmut", a: { Dark: 1, Hauling: 1 } },
    { n: "Casquimou", en: "Helmut", f: "Forme des neiges", i: "helmut-snowfield-form", a: { Ice: 1, Dark: 1, Hauling: 1 } },
    { n: "Casquipreux", en: "Pawney", i: "pawney", a: { Dark: 3, Hauling: 3 } },
    { n: "Casquipreux", en: "Pawney", f: "Forme prismana", i: "pawney-prismana-form", a: { Dark: 4, Hauling: 4 } },
    { n: "Casquipreux", en: "Pawney", f: "Forme des neiges", i: "pawney-snowfield-form", a: { Ice: 2, Dark: 3, Hauling: 3 } },
    { n: "Casquipreux", en: "Pawney", f: "Forme Ombrarc", i: "pawney-umbrabow-form", a: { Dark: 3, Hauling: 1 } },
    { n: "Clairbec", en: "Cornet", i: "cornet", a: { Wind: 3 } },
    { n: "Clairbec", en: "Cornet", f: "Forme des plages", i: "cornet-beach-form", a: { Water: 2, Wind: 3 } },
    { n: "Clairbec", en: "Cornet", f: "Hautes-plaines", i: "cornet-highland-form", a: { Grass: 2, Wind: 3 } },
    { n: "Clairbec", en: "Cornet", f: "Forme prismana", i: "cornet-prismana-form", a: { Lightning: 3, Wind: 4 } },
    { n: "Clairbec", en: "Cornet", f: "Forme Ombrarc", i: "cornet-umbrabow-form", a: { Lightning: 3, Wind: 3 } },
    { n: "Coléobée", en: "Waleetle", i: "waleetle", a: { Earth: 3, Hauling: 3 } },
    { n: "Coléobée", en: "Waleetle", f: "Forme prismana", i: "waleetle-prismana-form", a: { Earth: 4, Dark: 3, Hauling: 4 } },
    { n: "Coléobée", en: "Waleetle", f: "Forme des neiges", i: "waleetle-snowfield-form", a: { Earth: 3, Ice: 2, Hauling: 3 } },
    { n: "Coracroc", en: "Reefish", i: "reefish", a: { Water: 1, Earth: 1 } },
    { n: "Coracroc", en: "Reefish", f: "Forme des déluges", i: "reefish-rainstorm-form", a: { Earth: 1 } },
    { n: "Coraleurre", en: "Coraliz", i: "coraliz", a: { Water: 1, Earth: 1, Hauling: 1 } },
    { n: "Coraleurre", en: "Coraliz", f: "Forme des déluges", i: "coraliz-rainstorm-form", a: { Earth: 1, Hauling: 1 } },
    { n: "Crabiflore", en: "Shrubclaw", i: "shrubclaw", a: { Grass: 2, Earth: 3, Hauling: 3 } },
    { n: "Crabiflore", en: "Shrubclaw", f: "Forme des baies / Forme des plages / Forme des vasières", i: "shrubclaw-bay-form", a: { Earth: 3, Hauling: 3 } },
    { n: "Crabourgeon", en: "Budclaw", i: "budclaw", a: { Grass: 1, Earth: 1, Hauling: 1 } },
    { n: "Crabourgeon", en: "Budclaw", f: "Forme des baies / Forme des plages / Forme des vasières", i: "budclaw-bay-form", a: { Earth: 1, Hauling: 1 } },
    { n: "Cristocrabe", en: "Geoclaw", i: "geoclaw", a: { Ice: 3, Hauling: 3 } },
    { n: "Cristorex", en: "Minespine", i: "minespine", a: { Earth: 3, Hauling: 3 } },
    { n: "Cuicui", en: "Chirpi", i: "chirpi", a: { Wind: 1 } },
    { n: "Cuicui", en: "Chirpi", f: "Forme des plages", i: "chirpi-beach-form", a: { Water: 1, Wind: 1 } },
    { n: "Cuicui", en: "Chirpi", f: "Hautes-plaines", i: "chirpi-highland-form", a: { Grass: 1, Wind: 1 } },
    { n: "Cuiragon", en: "Helgon", i: "helgon", a: { Wind: 3, Hauling: 3 } },
    { n: "Cumulaine", en: "Nimbi", i: "nimbi", a: { Wind: 1, Leisure: 1 } },
    { n: "Cumulaine", en: "Nimbi", f: "Forme des plateaux", i: "nimbi-plateau-form", a: { Ice: 1, Wind: 1, Leisure: 1 } },
    { n: "Cumulaine", en: "Nimbi", f: "Forme des déluges", i: "nimbi-rainstorm-form", a: { Lightning: 1, Wind: 1, Leisure: 1 } },
    { n: "Célestia", en: "Celestis", i: "celestis", a: { Dark: 1, Leisure: 1 } },
    { n: "Danzard", en: "Dazmand", i: "dazmand", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Eko", en: "Eko", i: "eko", a: { Wind: 1, Artisanship: 1 } },
    { n: "Ekolombo", en: "Eklue", i: "eklue", a: { Wind: 3, Artisanship: 3 } },
    { n: "Elfe solidaire", en: "Sparkelf", i: "sparkelf", a: { Fire: 3 } },
    { n: "Elfe solidaire", en: "Sparkelf", f: "Forme prismana", i: "sparkelf-prismana-form", a: { Fire: 4 } },
    { n: "Fabulle", en: "Erlath", i: "erlath", a: { Water: 3 } },
    { n: "Falou", en: "Fahloo", i: "fahloo", a: { Water: 1 } },
    { n: "Farfafeu", en: "Sparki", i: "sparki", a: { Fire: 2 } },
    { n: "Fennelune", en: "Fennelun", i: "fennelun", a: { Light: 3, Hauling: 3 } },
    { n: "Filoutus", en: "Pranky", i: "pranky", a: { Water: 2, Hauling: 2 } },
    { n: "Filoutus", en: "Pranky", f: "Forme des neiges", i: "pranky-snowfield-form", a: { Water: 2, Ice: 1, Hauling: 2 } },
    { n: "Flamirage", en: "Flamerion", i: "flamerion", a: { Fire: 3 } },
    { n: "Flammi", en: "Wisptis", i: "wisptis", a: { Dark: 1, Artisanship: 1 } },
    { n: "Flammi", en: "Wisptis", f: "Forme des forêts", i: "wisptis-forest-form", a: { Grass: 1, Dark: 1, Artisanship: 1 } },
    { n: "Flammi", en: "Wisptis", f: "Hautes-plaines", i: "wisptis-highland-form", a: { Fire: 1, Dark: 1, Artisanship: 1 } },
    { n: "Fluoretti", en: "Flutternym", i: "flutternym", a: { Wind: 1, Leisure: 1 } },
    { n: "Fluoretti", en: "Flutternym", f: "Forme des montagnes boisées", i: "flutternym-mountain-woods-form", a: { Earth: 1, Wind: 1, Leisure: 1 } },
    { n: "Fluoretti", en: "Flutternym", f: "Forme nocturne", i: "flutternym-nighttime-form", a: { Wind: 1, Dark: 1, Leisure: 1 } },
    { n: "Fluoretti", en: "Flutternym", f: "Forme des mers florales", i: "flutternym-sea-of-flowers-form", a: { Grass: 1, Wind: 1, Leisure: 1 } },
    { n: "Fragrancier", en: "Fragrancier", i: "fragrancier", a: { Dark: 3, Leisure: 3, Perfumery: 3 } },
    { n: "Fredon", en: "Hummin", i: "hummin", a: { Grass: 1 } },
    { n: "Fulgucrin", en: "Fenmane", i: "fenmane", a: { Lightning: 3, Hauling: 3 } },
    { n: "Fulgucrin", en: "Fenmane", f: "Forme prismana", i: "fenmane-prismana-form", a: { Lightning: 4, Light: 3, Hauling: 3, Artisanship: 4 } },
    { n: "Fulmi", en: "Fulmintis", i: "fulmintis", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Fulmi", en: "Fulmintis", f: "Forme prismana", i: "fulmintis-prismana-form", a: { Lightning: 4, Light: 3, Artisanship: 4 } },
    { n: "Gachapoulpe", en: "Gachapus", i: "gachapus", a: { Water: 3, Artisanship: 3 } },
    { n: "Givrotus", en: "Glacy", i: "glacy", a: { Water: 3, Ice: 2, Hauling: 3 } },
    { n: "Givrotus", en: "Glacy", f: "Forme prismana", i: "glacy-prismana-form", a: { Water: 4, Light: 3, Hauling: 4 } },
    { n: "Glaivrier", en: "Fenrier", i: "fenrier", a: { Ice: 2, Hauling: 2 } },
    { n: "Glaivrier", en: "Fenrier", f: "Forme nocturne", i: "fenrier-nighttime-form", a: { Ice: 2, Dark: 1, Hauling: 2 } },
    { n: "Grizzo", en: "Grizbo", i: "grizbo", a: { Earth: 3, Hauling: 3 } },
    { n: "Grizzo", en: "Grizbo", f: "Forme prismana", i: "grizbo-prismana-form", a: { Earth: 4, Dark: 3, Hauling: 4 } },
    { n: "Géodosaure", en: "Geodeback", i: "geodeback", a: { Earth: 2, Hauling: 2 } },
    { n: "Hurlebrasier", en: "Scorchhowl", i: "scorchhowl", a: { Fire: 3, Hauling: 3 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Hautes-plaines", i: "scorchhowl-highland-form", a: { Fire: 3, Earth: 2, Hauling: 3 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Forme prismana", i: "scorchhowl-prismana-form", a: { Fire: 4, Hauling: 4 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Forme des orages", i: "scorchhowl-thunderstorm-form", a: { Fire: 3, Lightning: 2, Hauling: 3 } },
    { n: "Hurlebrasier", en: "Scorchhowl", f: "Forme Ombrarc", i: "scorchhowl-umbrabow-form", a: { Fire: 3, Hauling: 1 } },
    { n: "Hélion", en: "Helion", i: "helion", a: { Light: 3, Hauling: 3 } },
    { n: "Igniti", en: "Ignitis", i: "ignitis", a: { Dark: 3, Artisanship: 3 } },
    { n: "Igniti", en: "Ignitis", f: "Forme des forêts", i: "ignitis-forest-form", a: { Grass: 2, Dark: 3, Artisanship: 3 } },
    { n: "Igniti", en: "Ignitis", f: "Hautes-plaines", i: "ignitis-highland-form", a: { Fire: 2, Dark: 3, Artisanship: 3 } },
    { n: "Igniti", en: "Ignitis", f: "Forme prismana", i: "ignitis-prismana-form", a: { Fire: 3, Dark: 4, Artisanship: 4 } },
    { n: "Igniti", en: "Ignitis", f: "Forme Ombrarc", i: "ignitis-umbrabow-form", a: { Fire: 3, Dark: 3, Artisanship: 3 } },
    { n: "Infergon", en: "Infergon", i: "infergon", a: { Fire: 3, Hauling: 3 } },
    { n: "Infergon", en: "Infergon", f: "Forme prismana", i: "infergon-prismana-form", a: { Fire: 4, Wind: 3, Hauling: 4 } },
    { n: "Inferlupin", en: "Inferlupa", i: "inferlupa", a: { Fire: 2, Dark: 3, Hauling: 3 } },
    { n: "Inferlupin", en: "Inferlupa", f: "Forme prismana", i: "inferlupa-prismana-form", a: { Fire: 3, Dark: 4, Hauling: 4 } },
    { n: "Iris", en: "Iris", i: "iris", a: { Grass: 1, Leisure: 1 } },
    { n: "Jappardent", en: "Flameruff", i: "flameruff", a: { Fire: 2, Hauling: 2 } },
    { n: "Jappardent", en: "Flameruff", f: "Hautes-plaines", i: "flameruff-highland-form", a: { Fire: 2, Earth: 1, Hauling: 2 } },
    { n: "Lainirique", en: "Dreaple", i: "dreaple", a: { Dark: 3, Leisure: 3 } },
    { n: "Lavasaure", en: "Lavazar", i: "lavazar", a: { Fire: 2, Earth: 1, Hauling: 2 } },
    { n: "Loufeuteau", en: "Emberpup", i: "emberpup", a: { Fire: 1, Hauling: 1 } },
    { n: "Loufeuteau", en: "Emberpup", f: "Hautes-plaines", i: "emberpup-highland-form", a: { Fire: 1, Earth: 1, Hauling: 1 } },
    { n: "Louloutre", en: "Susuta", i: "susuta", a: { Water: 1, Leisure: 1 } },
    { n: "Luminelle", en: "Luminelle", i: "luminelle", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Luminelle", en: "Luminelle", f: "Forme prismana", i: "luminelle-prismana-form", a: { Lightning: 4, Light: 3, Artisanship: 4 } },
    { n: "Luminelle", en: "Luminelle", f: "Forme des déluges", i: "luminelle-rainstorm-form", a: { Water: 2, Lightning: 3, Artisanship: 3 } },
    { n: "Luminelle", en: "Luminelle", f: "Forme Ombrarc", i: "luminelle-umbrabow-form", a: { Lightning: 4, Light: 4 } },
    { n: "Lumiris", en: "Irisalis", i: "irisalis", a: { Grass: 4, Leisure: 4 } },
    { n: "Lunara", en: "Lunara", i: "lunara", a: { Light: 3, Hauling: 3 } },
    { n: "Magmarex", en: "Magmarex", i: "magmarex", a: { Fire: 3, Earth: 2, Hauling: 3 } },
    { n: "Magmarex", en: "Magmarex", f: "Forme prismana", i: "magmarex-prismana-form", a: { Fire: 4, Dark: 3, Hauling: 4 } },
    { n: "Magmarex", en: "Magmarex", f: "Forme Ombrarc", i: "magmarex-umbrabow-form", a: { Fire: 3, Dark: 3, Leisure: 3 } },
    { n: "Malaglace", en: "Malevsera", i: "malevsera", a: { Ice: 3, Artisanship: 3 } },
    { n: "Malange", en: "Malangel", i: "malangel", a: { Ice: 1, Artisanship: 1 } },
    { n: "Mandibouille", en: "Jawling", i: "jawling", a: { Wind: 1, Hauling: 1 } },
    { n: "Mimijoue", en: "Cheekie", i: "cheekie", a: { Ice: 1, Hauling: 1 } },
    { n: "Molosabre", en: "Glynsera", i: "glynsera", a: { Ice: 3, Hauling: 3 } },
    { n: "Molosabre", en: "Glynsera", f: "Forme nocturne", i: "glynsera-nighttime-form", a: { Ice: 3, Dark: 2, Hauling: 3 } },
    { n: "Molosabre", en: "Glynsera", f: "Forme prismana", i: "glynsera-prismana-form", a: { Ice: 4, Light: 3, Hauling: 4 } },
    { n: "Morsou", en: "Wavwal", i: "wavwal", a: { Ice: 3, Hauling: 1 } },
    { n: "Méliflore", en: "Melloblum", i: "melloblum", a: { Grass: 3, Artisanship: 3 } },
    { n: "Méliflore", en: "Melloblum", f: "Forme prismana", i: "melloblum-prismana-form", a: { Grass: 4, Light: 3, Artisanship: 4 } },
    { n: "Nutrion", en: "Tuckin", i: "tuckin", a: { Grass: 3, Hauling: 3 } },
    { n: "Nutrion", en: "Tuckin", f: "Forme des montagnes", i: "tuckin-mountain-form", a: { Grass: 3, Earth: 2, Hauling: 3 } },
    { n: "Ondeloutre", en: "Piopiota", i: "piopiota", a: { Water: 3, Leisure: 3 } },
    { n: "Ondeloutre", en: "Piopiota", f: "Forme nocturne", i: "piopiota-nighttime-form", a: { Water: 3, Dark: 2, Leisure: 3 } },
    { n: "Osky", en: "Bonesky", i: "bonesky", a: { Ice: 1, Hauling: 1 } },
    { n: "Osky", en: "Bonesky", f: "Forme nocturne", i: "bonesky-nighttime-form", a: { Ice: 1, Dark: 1, Hauling: 1 } },
    { n: "Ourso", en: "Cubbo", i: "cubbo", a: { Earth: 1, Hauling: 1 } },
    { n: "Pebbling", en: "Pebbling", i: "pebbling", a: { Earth: 1, Hauling: 1 } },
    { n: "Plumiel", en: "Dewy", i: "dewy", a: { Dark: 1, Leisure: 1, Perfumery: 1 } },
    { n: "Pomawk", en: "Pomawk", i: "pomawk", a: { Grass: 3, Artisanship: 3 } },
    { n: "Pomawk", en: "Pomawk", f: "Forme des neiges", i: "pomawk-snowfield-form", a: { Grass: 3, Ice: 2, Artisanship: 3 } },
    { n: "Pomœuf", en: "Pomegg", i: "pomegg", a: { Grass: 1, Artisanship: 1 } },
    { n: "Pomœuf", en: "Pomegg", f: "Forme des neiges", i: "pomegg-snowfield-form", a: { Grass: 1, Ice: 1, Artisanship: 1 } },
    { n: "Poulplash", en: "Popapus", i: "popapus", a: { Water: 3 } },
    { n: "Pulsato", en: "Besauce", i: "besauce", a: { Lightning: 3, Artisanship: 1 } },
    { n: "Rapiéronce", en: "Thornblade", i: "thornblade", a: { Grass: 3, Artisanship: 3 } },
    { n: "Rapiéronce", en: "Thornblade", f: "Forme prismana", i: "thornblade-prismana-form", a: { Grass: 4, Water: 3, Artisanship: 4 } },
    { n: "Rapiéronce", en: "Thornblade", f: "Forme des orages", i: "thornblade-rainstorm-form", a: { Grass: 3, Lightning: 2, Artisanship: 3 } },
    { n: "Rapiéronce", en: "Thornblade", f: "Forme Ombrarc", i: "thornblade-umbrabow-form", a: { Grass: 3, Water: 3, Artisanship: 3 } },
    { n: "Soléon", en: "Soleon", i: "soleon", a: { Light: 3, Hauling: 3 } },
    { n: "Sorcelonde", en: "Hexxin", i: "witchin", a: { Grass: 1, Dark: 2, Artisanship: 2 } },
    { n: "Sorcelonde", en: "Hexxin", f: "Forme prismana", i: "witchin-prismana-form", a: { Grass: 3, Dark: 4, Artisanship: 4 } },
    { n: "Sorcelonde", en: "Hexxin", f: "Forme Ombrarc", i: "witchin-umbrabow-form", a: { Grass: 2, Dark: 2 } },
    { n: "Stellaria", en: "Stellarys", i: "stellarys", a: { Dark: 3, Leisure: 3 } },
    { n: "Stellaria", en: "Stellarys", f: "Forme prismana", i: "stellarys-prismana-form", a: { Ice: 3, Dark: 4, Leisure: 4 } },
    { n: "Stellaria", en: "Stellarys", f: "Forme des déluges", i: "stellarys-rainstorm-form", a: { Water: 2, Dark: 3, Leisure: 3 } },
    { n: "Stellaria", en: "Stellarys", f: "Forme Ombrarc", i: "stellarys-umbrabow-form", a: { Ice: 3, Dark: 3, Leisure: 3 } },
    { n: "Terriloutre", en: "Panpanta", i: "panpanta", a: { Water: 3, Leisure: 3 } },
    { n: "Terriloutre", en: "Panpanta", f: "Forme prismana", i: "panpanta-prismana-form", a: { Water: 4, Leisure: 4 } },
    { n: "Tilotus", en: "Skippy", i: "skippy", a: { Water: 1, Hauling: 1 } },
    { n: "Tilotus", en: "Skippy", f: "Forme des neiges", i: "skippy-snowfield-form", a: { Water: 1, Ice: 1, Hauling: 1 } },
    { n: "Touffu", en: "Fentuft", i: "fentuft", a: { Lightning: 1, Hauling: 1 } },
    { n: "Trombec", en: "Tromber", i: "tromber", a: { Wind: 3 } },
    { n: "Trombec", en: "Tromber", f: "Forme des plages", i: "tromber-beach-form", a: { Water: 2, Wind: 3 } },
    { n: "Trombec", en: "Tromber", f: "Hautes-plaines", i: "tromber-highland-form", a: { Grass: 2, Wind: 3 } },
    { n: "Tubabec", en: "Tubster", i: "tubster", a: { Wind: 3 } },
    { n: "Tubabec", en: "Tubster", f: "Forme des plages", i: "tubster-beach-form", a: { Water: 2, Wind: 3 } },
    { n: "Tubabec", en: "Tubster", f: "Hautes-plaines", i: "tubster-highland-form", a: { Grass: 2, Wind: 3 } },
    { n: "Turbulaine", en: "Turbo", i: "turbo", a: { Wind: 3, Leisure: 3 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme des plateaux", i: "turbo-plateau-form", a: { Ice: 2, Wind: 3, Leisure: 3 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme prismana", i: "turbo-prismana-form", a: { Wind: 4, Dark: 3, Leisure: 4 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme des déluges", i: "turbo-rainstorm-form", a: { Lightning: 2, Wind: 3, Leisure: 3 } },
    { n: "Turbulaine", en: "Turbo", f: "Forme Ombrarc", i: "turbo-umbrabow-form", a: { Wind: 3, Dark: 3, Leisure: 3 } },
    { n: "Valsiris", en: "Irisal", i: "irisal", a: { Grass: 3, Leisure: 3 } },
    { n: "Valsiris", en: "Irisal", f: "Forme prismana", i: "irisal-prismana-form", a: { Grass: 4, Leisure: 4 } },
    { n: "Vitti", en: "Somniwing", i: "somniwing", a: { Grass: 4, Wind: 3, Leisure: 4 } },
    { n: "Voilotus", en: "Leafy", i: "leafy", a: { Grass: 3, Water: 2, Hauling: 3 } },
    { n: "Voilueur", en: "Veilfloat", i: "veilfloat", a: { Lightning: 2, Artisanship: 2 } },
    { n: "Voletti", en: "Gracewing", i: "gracewing", a: { Wind: 3, Leisure: 3 } },
    { n: "Voletti", en: "Gracewing", f: "Forme des montagnes boisées", i: "gracewing-mountain-woods-form", a: { Earth: 2, Wind: 3, Leisure: 3 } },
    { n: "Voletti", en: "Gracewing", f: "Forme nocturne", i: "gracewing-nighttime-form", a: { Wind: 3, Dark: 2, Leisure: 3 } },
    { n: "Voletti", en: "Gracewing", f: "Forme des mers florales", i: "gracewing-sea-of-flowers-form", a: { Grass: 2, Wind: 3, Leisure: 3 } },
    { n: "Voltige", en: "Bolty", i: "bolty", a: { Lightning: 1, Artisanship: 1 } },
    { n: "Voltignasse", en: "Blazen", i: "blazen", a: { Lightning: 3, Artisanship: 3 } },
    { n: "Voltignasse", en: "Blazen", f: "Forme prismana", i: "blazen-prismana-form", a: { Lightning: 4, Dark: 3, Artisanship: 4 } },
    { n: "Voltignasse", en: "Blazen", f: "Forme Ombrarc", i: "blazen-umbrabow-form", a: { Lightning: 3, Dark: 3, Artisanship: 3 } },
    { n: "Écurixe", en: "Squarrel", i: "squarrel", a: { Fire: 1, Artisanship: 1 } },
    { n: "Écurouste", en: "Squashel", i: "squashel", a: { Fire: 2, Artisanship: 2 } },
];

export const ANIIMO_SOURCE = { name: 'wikily.gg', url: 'https://wikily.gg/fr/aniimo/aniilog', date: '2026-10-03' };
